spring:
  graphql:
    path: /graphql
    schema:
      printer:
        enabled: true

#  r2dbc:
#    url: r2dbc:h2:file://./build/database/db;AUTO_SERVER=TRUE
#    username: user
#    password: password
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/test-data
#    url: jdbc:h2:./build/database/db;AUTO_SERVER=TRUE
  datasource:
    url: jdbc:h2:./build/database/db;AUTO_SERVER=TRUE
    username: user
    password: password
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
